### ISSUE TITLE
null loaded as string

### ISSUE THREAD

**Issue by achalddave** [gvvaughan/lyaml#13]
It seems `null` is parsed as a string in lyaml instead of as a 'nil' type, unless I'm missing something. Here's an example showing the issue, and a comparison with what Python does.

https://gist.github.com/achalddave/0c8acc998acb21b4372d02d0b0650b12

**Comment by gvvaughan** [comment]
Thanks for the report; I can't believe I missed that every time I read the spec docs!

In order to be compliant with the spec, which requires support of null keys into maps, we can't map yaml `null` directly onto Lua `nil`, but with this commit we do at least get `lyaml.null` objects.
