### ISSUE TITLE
./configure have error

### ISSUE THREAD

**Issue by redfox241** [gvvaughan/lyaml#15]
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for specl... /usr/local/bin/specl
checking for ldoc... /usr/local/bin/ldoc
checking for a Lua interpreter with version >= 5.1, < 5.4... lua
checking for lua... /usr/bin/lua
checking for lua version... 5.1
checking for lua platform... unknown
checking for lua script directory... ${prefix}/share/lua/5.1
checking for lua module directory... ${exec_prefix}/lib/lua/5.1
checking for ANSI C header files... (cached) yes
checking if LUA_VERSION is defined... yes
checking lua.h usability... no
checking lua.h presence... no
checking for lua.h... no
checking lualib.h usability... no
checking lualib.h presence... no
checking for lualib.h... no
checking lauxlib.h usability... no
checking lauxlib.h presence... no
checking for lauxlib.h... no
checking luaconf.h usability... no
checking luaconf.h presence... no
checking for luaconf.h... no
**configure: error: cannot find Lua includes**

**Comment by gvvaughan** [comment]
it's all in the error message. You can look at config.log to see details of where it is looking for your headers. You can set CPPFLAGS in configure's execution environment to point at the directory containing your lua headers, and also look at m4/ax_lua.m4 (particularly the detailed instructions at the top) to discover how the headers are found.

HTH,
Gary
