### ISSUE TITLE
specl: command not found

### ISSUE THREAD

**Issue by luckypoem** [gvvaughan/lyaml#19]
hi.

root@localhost:~/lyaml# specl -v1freport specs/*_spec.yaml
No command 'specl' found, did you mean:
 Command 'pecl' from package 'php-pear' (main)
 Command 'spell' from package 'spell' (main)
specl: command not found
root@localhost:~/lyaml# find . -name specl
root@localhost:~/lyaml#

how to fix it?

**Comment by gvvaughan** [comment]
specl is my rspec inspired lua test framework over lyaml. You can install it with luarocks:

  luarocks install specl
