### ISSUE TITLE
Is this available on OPM

### ISSUE THREAD

**Issue by bharatraj88** [gvvaughan/lyaml#28]
Hello @gvvaughan ,

I understand that this lib is available over lua rocks.

Can you please let me know if this is available on OPM [https://opm.openresty.org] as openResty has deprecated packages over lua rocks

**Comment by gvvaughan** [comment]
Hi,

Sorry for the late reply.  No, I don't upload to openresty.org, though you are welcome to do so on my behalf if you would like.
