### ISSUE TITLE
emit_SCALAR does not use `plain_implicit` and `quoted_implicit` from lua

### ISSUE THREAD

**Issue by Dude112113** [gvvaughan/lyaml#36]
`plain_implicit` and `quoted_implicit` on the following line https://github.com/gvvaughan/lyaml/blob/master/ext/yaml/emitter.c#L256 do not actually get set, though it should be set from the values in lua.  
You do use these on these in lyaml at
https://github.com/gvvaughan/lyaml/blob/master/lib/lyaml/init.lua#L154-L155

I found this while making my own dumper using the emitter and could not emit tags for scalars.
~If you would like I can make a pull request to fix this.~ PR: #37

**Comment by gvvaughan** [comment]
By all means!

**Comment by Dude112113** [comment]
Sorry for all the mess, I was figuring out how to squash commits (Im still rather new to git)
The the tavis stuff passes then its ready to merge or what not.

**Comment by gvvaughan** [comment]
Thank you so much for working on this!

Git does get easier the more you use it, I promise.

Do you have a reproducer for the bug that I can turn into a test case to commit with your fix, please?

**Comment by gvvaughan** [comment]
btw, once I have this in, I'll make a new release and upload it to luarocks.

**Comment by Dude112113** [comment]
I will work on that later today for you

**Comment by Dude112113** [comment]
I have committed an addition to your tests, adding tests for plain_implicit, quoted_implicit and tags.
I'd advise you to look at them before you merge anything as I had no idea how it worked and took a look at other tests to figure it out.
And the test for the tag is using both plain_implicit, quoted_implicit as false as it is required for the test, I belive that should be fine though.
