### ISSUE TITLE
Support Installation from Brew for MacOS

### ISSUE THREAD

**Issue by nasrulhazim** [gvvaughan/lyaml#44]
Hi,

Would this package able to install using Brew? 

I've tried but no luck at the moment to install it with Brew. Following are the Brew script generated using `brew create ...`:

```ruby
class Lyaml < Formula
  desc "LibYAML binding for Lua"
  homepage "https://gvvaughan.github.io/lyaml"
  url "https://github.com/gvvaughan/lyaml/archive/refs/tags/v6.2.7.tar.gz"
  sha256 "9bb489cefae48b150d66f6bab4141d8d5831fcb7465bfc52a9845fa01efc63b0"
  license "MIT"

  def install
    system "./configure", *std_configure_args, "--disable-silent-rules"
  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # This test will fail and we won't accept that! For Homebrew/homebrew-core
    # this will need to be a test that verifies the functionality of the
    # software. Run the test with `brew test lyaml`. Options passed
    # to `brew install` such as `--HEAD` also need to be provided to `brew test`.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    system "false"
  end
end
```

I have issue when install the Kong Gateway, which depends on this package - no package available in Brew yet for lyaml.

**Comment by gvvaughan** [comment]
Why not install  luarocks from homebrew, and then use luarocks to install lyaml?

If you really want a special homebrew lyaml package, you can ask in https://github.com/Homebrew/homebrew-core for help in submitting and maintaining a recipe.

**Comment by alerque** [comment]
One of the issues with the way Homebrew packaging works is it is very hard to install a library package and have it accessible to other app packages. This is especially true for Lua. You'll notice that many Lua apps that are packaged have to install copies of their Lua library dependencies as part of their own packaging; any other way they are inaccessible. See `Formula/sile.rb` for an example.

You would have to talk to Homebrew folks for more details, but until there is a pattern to follow for packaging Lua libraries I don't think this or any other Lua project can do much towards their own packaging.
