### ISSUE TITLE
Feature request: sort keys on generated yaml

### ISSUE THREAD

**Issue by kikito** [gvvaughan/lyaml#45]
I was wondering if it would be possible to add a flag to sort keys in arrays before generating?

**Comment by gvvaughan** [comment]
Hi, there’s no need - you can use the low level emitter interface to send document tokens for keys in any order you’d like. If you need some inspiration for how to implement that, you can start with a copy of `dumper_mt` in lib/lyaml/init.lua and tweak accordingly. Alternatively, take a look at my Specl project, which also calls the low level interfaces to add line number tracking for displaying nicer error messages.

**Comment by kikito** [comment]
Thank you for the directions, I will give this a try.
