### ISSUE TITLE
Keeping structure order

### ISSUE THREAD

**Issue by solisoft** [gvvaughan/lyaml#50]
It is possible to keep the YAML structure order ?

let say this yaml string
```yaml
key1: 1
key2: 2
key2: 3
```

```lua
lyaml.load(my_yaml_string) 
```

will return 
```
{
key33
key11
key22
}
```

or 
```
{
key11
key33
key22
}
```

or any another combination. 

It is possible to keep the order?

**Comment by gvvaughan** [comment]
Not exactly. Neither YAML maps nor Lua tables store keys in order.

If you just want a stable order in Lua, you could sort a list of keys and access thedict elements in that order.

If exact (but unsorted) order is required you'd have to write your YAML as a list of one element dictionaries:

```
- key1: 1
- key2: 2
- key3: 3
```
